<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN" Id="{b9a671a8-df30-4416-a74a-a1d58cfcceb8}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbPizzaOven : FB_PizzaOven ;
	bLoadPizza				: BOOL; //InsertPizza button
	bRemovePizza			: BOOL; //PackagePizza button
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbPizzaOven(bLoadPizza := bLoadPizza, bRemovePizza := bRemovePizza);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>